-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgIyLWtacS/fCzxZUgpixmZxQRzYtm3soVnLgTBSDjGBqgCgYIKoZIzj0DAQehRANCAATfzBwyUmHG8nBJsjvdPBDdZGvKnvbggtWMu4CUSLqI7XQvJ+Wj5bsEJXnZYNzOX1Fw4ecJsuLWaDd9QbfmZ7JB
-----END PRIVATE KEY-----